# Framework for running automated tests on OSB using Travis-CI, see https://github.com/OpenSourceBrain/osb-model-validation

dist: bionic

language: python

python:
    #- 2.7 # disable for efficiency
    - 3.7

env:
    #- OMV_ENGINE=NEURON:7.5
    - OMV_ENGINE=NEURON:7.6
    - OMV_ENGINE=NEURON:7.7
    - OMV_ENGINE=NEURON     # default version
    - OMV_ENGINE=jNeuroML
    - OMV_ENGINE=jNeuroML_NEURON
    - OMV_ENGINE=jNeuroML_validate
    - OMV_ENGINE=jNeuroML_validatev1

install:
    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation

script:
    - omv all -V
    - omv list -V
